In [8]:
#creating nd array

#0d array
import numpy as np
arr=np.array(42)
print(arr)

#1d array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

#2d array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

#3D ARRAY
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

#creating an array of zero's
arr=np.zeros((2,3))
print(arr)
#creating an array of one's
arr=np.ones((2,3))
print(arr)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#arithmatic operation on array
import numpy as np
a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])
d=np.add(a,b)
c=a+b
e=np.subtract(a,b)#using substraction function
i=a-b#using substraction operator
f=np.multiply(a,b)#using multiplication function
j=a*b#using multiplication operator
g=np.divide(a,b)#using division function
k=a/b#using division operator
h=np.mod(a,b)#using mod function
l=a%b#using mod operator
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)



[ 13  24 105 206 507]
[ 13  24 105 206 507]
[  7  16  95 194 493]
[  30   80  500 1200 3500]
[ 3.33333333  5.         20.         33.33333333 71.42857143]
[1 0 0 2 3]
[  7  16  95 194 493]
[  30   80  500 1200 3500]
[ 3.33333333  5.         20.         33.33333333 71.42857143]
[1 0 0 2 3]


In [23]:
#power function
import numpy as np
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
c=np.power(a,b)
print(c)
#square root function
d=np.sqrt(a)
print(d)
#exponential function
e=np.exp(a)
print(e)
#log function
f=np.log(a)
print(f)
#log10 function
g=np.log10(a)
print(g)
#log2 function
h=np.log2(a)
print(h)
#sin function
i=np.sin(a)
print(i)
#cos function
j=np.cos(a)
print(j)
#tan function
k=np.tan(a)
print(k)
#sinh function
l=np.sinh(a)
print(l)
#cosh function
m=np.cosh(a)
print(m)
#tanh function
n=np.tanh(a)
print(n)


[  343    81  1024 15625     1]
[2.64575131 1.73205081 2.         2.23606798 1.        ]
[1096.63315843   20.08553692   54.59815003  148.4131591     2.71828183]
[1.94591015 1.09861229 1.38629436 1.60943791 0.        ]
[0.84509804 0.47712125 0.60205999 0.69897    0.        ]
[2.80735492 1.5849625  2.         2.32192809 0.        ]
[ 0.6569866   0.14112001 -0.7568025  -0.95892427  0.84147098]
[ 0.75390225 -0.9899925  -0.65364362  0.28366219  0.54030231]
[ 0.87144798 -0.14254654  1.15782128 -3.38051501  1.55740772]
[548.31612327  10.01787493  27.2899172   74.20321058   1.17520119]
[548.31703516  10.067662    27.30823284  74.20994852   1.54308063]
[0.99999834 0.99505475 0.9993293  0.9999092  0.76159416]
